name = "SampleChainsDynamicHMC"
uuid = "6d9fd711-e8b2-4778-9c70-c1dfb499d4c4"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "0.3.4"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DynamicHMC = "bbc10e6e-7c05-544b-b16e-64fede858acb"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
NestedTuples = "a734d2a7-8d68-409b-9419-626914d4061d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SampleChains = "754583d1-7fc4-4dab-93b5-5eaca5c9622e"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
TupleVectors = "615932cf-77b6-4358-adcd-5b7eba981d7e"

[compat]
ConcreteStructs = "0.2"
DynamicHMC = "3.1"
ElasticArrays = "1.2"
LogDensityProblems = "0.10"
MappedArrays = "0.3,0.4"
NestedTuples = "0.2, 0.3"
Reexport = "1"
SampleChains = "0.5"
StructArrays = "0.5"
TransformVariables = "0.3, 0.4"
TupleVectors = "0.1"
julia = "1.5"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Logging", "ReverseDiff", "Test"]
